/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectGoogleRouteImport } from './routes/connect-google'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FirstAuditRouteImport } from './routes/first-audit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAiVisibilityRouteImport } from './routes/dashboard.ai-visibility'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectGoogleRoute = ConnectGoogleRouteImport.update({
  id: '/connect-google',
  path: '/connect-google',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAuditRoute = FirstAuditRouteImport.update({
  id: '/first-audit',
  path: '/first-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiVisibilityRoute = DashboardAiVisibilityRouteImport.update({
  id: '/ai-visibility',
  path: '/ai-visibility',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-google': typeof ConnectGoogleRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/first-audit': typeof FirstAuditRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/verify': typeof VerifyRoute
  '/dashboard/ai-visibility': typeof DashboardAiVisibilityRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-google': typeof ConnectGoogleRoute
  '/first-audit': typeof FirstAuditRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/verify': typeof VerifyRoute
  '/dashboard/ai-visibility': typeof DashboardAiVisibilityRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-google': typeof ConnectGoogleRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/first-audit': typeof FirstAuditRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/verify': typeof VerifyRoute
  '/dashboard/ai-visibility': typeof DashboardAiVisibilityRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-google'
    | '/dashboard'
    | '/first-audit'
    | '/login'
    | '/onboarding'
    | '/verify'
    | '/dashboard/ai-visibility'
    | '/dashboard/audit'
    | '/dashboard/content'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-google'
    | '/first-audit'
    | '/login'
    | '/onboarding'
    | '/verify'
    | '/dashboard/ai-visibility'
    | '/dashboard/audit'
    | '/dashboard/content'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/connect-google'
    | '/dashboard'
    | '/first-audit'
    | '/login'
    | '/onboarding'
    | '/verify'
    | '/dashboard/ai-visibility'
    | '/dashboard/audit'
    | '/dashboard/content'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectGoogleRoute: typeof ConnectGoogleRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FirstAuditRoute: typeof FirstAuditRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-google': {
      id: '/connect-google'
      path: '/connect-google'
      fullPath: '/connect-google'
      preLoaderRoute: typeof ConnectGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-audit': {
      id: '/first-audit'
      path: '/first-audit'
      fullPath: '/first-audit'
      preLoaderRoute: typeof FirstAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-visibility': {
      id: '/dashboard/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/dashboard/ai-visibility'
      preLoaderRoute: typeof DashboardAiVisibilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiVisibilityRoute: typeof DashboardAiVisibilityRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiVisibilityRoute: DashboardAiVisibilityRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectGoogleRoute: ConnectGoogleRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FirstAuditRoute: FirstAuditRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
